import { Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { STATUS_LABEL, type DomainReport } from '../domain/reportCard';
import { DOMAINS } from '../domain/domains';
import { formatDate } from './time';

/**
 * "Exportable PDF report" — Milestone spec §3: "parents can generate a PDF of
 * the report card / flag history to bring physically to a pediatrician
 * visit... useful even outside our tied-up network."
 *
 * The HTML here is deliberately the same report card a parent already sees
 * on screen — same status ladder, same one-line notes, same reassurance
 * copy if a flag is included — never the raw per-round numbers. A document a
 * parent might hand to an unaffiliated doctor must hold to the same
 * "no raw data, no condition names" rule as the screen it came from.
 *
 * Platform behaviour (SDK 57's own docs):
 *  - Web: `Print.printAsync` opens the browser's print dialog on the HTML
 *    directly — there is no real file to share, so that is also the whole
 *    export UX on web.
 *  - Native: `Print.printToFileAsync` writes an actual PDF into the app's
 *    cache, which is then handed to `Sharing.shareAsync` so it can go
 *    anywhere — a messaging app, mail, a printer.
 */

export type ExportInput = {
  childName: string;
  periodLabel: string;
  report: DomainReport[];
  flagSummary?: string | null;
};

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch] as string));
}

function buildHtml(input: ExportInput): string {
  const rows = input.report
    .map(
      r => `
      <tr>
        <td class="domain">${escapeHtml(DOMAINS[r.domain].label)}</td>
        <td class="status">${escapeHtml(STATUS_LABEL[r.status])}</td>
        <td class="note">${escapeHtml(r.note)}</td>
      </tr>`,
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #10201E; padding: 32px; }
  h1 { font-size: 22px; margin-bottom: 2px; }
  .sub { color: #7A8B84; font-size: 13px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  th, td { text-align: left; padding: 10px 8px; border-bottom: 1px solid #E4DDD1; font-size: 13px; vertical-align: top; }
  th { color: #7A8B84; font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; }
  .domain { font-weight: 600; width: 30%; }
  .status { width: 25%; }
  .flag { background: #E7ECFA; border: 1px solid #C3D0F1; border-radius: 10px; padding: 16px; font-size: 13px; margin-bottom: 16px; }
  .reassure { color: #475A55; font-size: 12px; margin-top: 24px; }
  .foot { color: #7A8B84; font-size: 11px; margin-top: 32px; }
</style>
</head>
<body>
  <h1>${escapeHtml(input.childName)}’s Khil report</h1>
  <div class="sub">${escapeHtml(input.periodLabel)} · generated ${escapeHtml(formatDate(Date.now()))}</div>

  ${input.flagSummary ? `<div class="flag"><strong>Worth a second look:</strong> ${escapeHtml(input.flagSummary)}<div class="reassure">This is not a diagnosis, and most flags do not turn out to indicate anything.</div></div>` : ''}

  <table>
    <thead><tr><th>Skill area</th><th>How it’s going</th><th>Note</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="3">Not enough play yet to report on.</td></tr>'}</tbody>
  </table>

  <div class="foot">Generated by Khil. A screening aid, not a diagnostic tool — any concern is always confirmed by a specialist directly.</div>
</body>
</html>`;
}

export async function exportReport(input: ExportInput): Promise<{ ok: boolean; reason?: string }> {
  const html = buildHtml(input);
  try {
    if (Platform.OS === 'web') {
      await Print.printAsync({ html });
      return { ok: true };
    }
    const { uri } = await Print.printToFileAsync({ html });
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) return { ok: false, reason: 'Sharing isn’t available on this device.' };
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf', dialogTitle: 'Share report' });
    return { ok: true };
  } catch {
    return { ok: false, reason: 'Couldn’t generate the report just now.' };
  }
}
