import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

/**
 * Short synthesised tones, generated by `scripts/generate-sounds.py` — no
 * licensed assets, and the sound design stays a parameter rather than a file
 * someone has to go and find.
 *
 * Deliberate choice: there is no "wrong answer" buzzer anywhere in Khil. The
 * failure sound is a soft falling third, because the child must never learn
 * that the app is testing them (wireframe 02, note 4).
 */
export type SoundName =
  | 'pad-1'
  | 'pad-2'
  | 'pad-3'
  | 'pad-4'
  | 'correct'
  | 'retry'
  | 'celebrate'
  | 'tap';

const SOURCES: Record<SoundName, number> = {
  'pad-1': require('../../assets/audio/pad-1.wav'),
  'pad-2': require('../../assets/audio/pad-2.wav'),
  'pad-3': require('../../assets/audio/pad-3.wav'),
  'pad-4': require('../../assets/audio/pad-4.wav'),
  correct: require('../../assets/audio/correct.wav'),
  retry: require('../../assets/audio/retry.wav'),
  celebrate: require('../../assets/audio/celebrate.wav'),
  tap: require('../../assets/audio/tap.wav'),
};

const players = new Map<SoundName, AudioPlayer>();

export async function prepareAudio(): Promise<void> {
  try {
    await setAudioModeAsync({
      playsInSilentMode: true,
      interruptionMode: 'mixWithOthers',
      shouldPlayInBackground: false,
    });
  } catch {
    /* audio session config is best-effort */
  }
}

function getPlayer(name: SoundName): AudioPlayer | null {
  const existing = players.get(name);
  if (existing) return existing;
  try {
    const player = createAudioPlayer(SOURCES[name]);
    players.set(name, player);
    return player;
  } catch {
    return null;
  }
}

export function playSound(name: SoundName): void {
  const player = getPlayer(name);
  if (!player) return;
  try {
    player.seekTo(0);
    player.play();
  } catch {
    /* a missing sound must never break a round */
  }
}

export function releaseSounds(): void {
  players.forEach(player => {
    try {
      player.remove();
    } catch {
      /* no-op */
    }
  });
  players.clear();
}
